### PR TITLE
Events for exceptions

### LINKED ISSUE #104: Expose exception, errors and warnings as event
Why:
- We want to monitor errors in application
- GamerHash will collect events in sentry
- We only expose errors

Requirements:
- Implement event exposing exceptions
- Different severity levels (error, warning)
- Optional: Attach broader context to Exception (for example GH currently attaches system and hardware information, maybe we have any Golem specific information that we would like to attach)

Technical details:
- IGolem exposes event ApplicationEvents
- GH app listens to events and sends them to sentry

ApplicationEvent:
- Exception
- Source (yagna, provider, activity loop)
- Message
- Severity
- Context (built during startup)
    - Golem configuration, state that could help in diagnosing problem
    - [Option] List all configuration values used to start yagna and provider (for example: presets, runtimes, env variables)
    - [Option] Requestor information

### PR DESCRIPTION
**Pull request by staszek-krotki**
Resolves #104

### CODE REVIEW

File: Golem/InvoiceEventsLoop.cs [hunk 1]
```diff
@@ -28,8 +31,9 @@ public async Task Start()
 
         await Task.Yield();
         
-        while (!_token.IsCancellationRequested)
+        while (true)
```
Comment (nieznanysprawiciel) [inline Golem/InvoiceEventsLoop.cs:34]: 👍🏻

File: Golem/Yagna/YagnaService.cs [hunk 2]
```diff
@@ -183,10 +187,6 @@ public async Task Run(Func<int, string, Task> exitHandler, CancellationToken can
                         YagnaProcess = null;
                     });
             }
-            catch (Exception)
-            {
-                throw;
-            }
```
Comment (nieznanysprawiciel) [inline Golem/Yagna/YagnaService.cs:189]: 👍🏻

File: Golem/Yagna/YagnaApi.cs [hunk 3]
```diff
@@ -111,9 +113,10 @@ public void Authorize(string key)
                 {
                     throw;
                 }
-                catch (Exception error)
+                catch (Exception e)
                 {
-                    _logger.LogError("Failed to get next stream event: {0}", error);
+                    _events.Raise(new ApplicationEventArgs("YagnaApi", $"Failed to get next stream event: {e.Message}", ApplicationEventArgs.SeverityLevel.Warning, e));
+                    _logger.LogError("Failed to get next stream event: {0}", e);
```
Comment (nieznanysprawiciel) [inline Golem/Yagna/YagnaApi.cs:119]: We could have function on EventsPublisher, that does both in one call. It will probably simplify many places in the future

File: Golem/InvoiceEventsLoop.cs [hunk 4]
```diff
@@ -43,13 +47,15 @@ public async Task Start()
                     }
                 }
             }
-            catch(TaskCanceledException)
+            catch(OperationCanceledException e)
```
Comment (nieznanysprawiciel) [inline Golem/InvoiceEventsLoop.cs:50]: 👍🏻
